### ISSUE TITLE
Change branch names in build/deploy.sh to main

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-next#104]
There's a few references to `master` in `_build/deploy.sh`. I was having issues with deploy (the first deploy step kept trying to run every time I tried to redeploy). When I changed these references to `main` the deploy appeared to work. I am not sure if making this change in deploy script will break anything so flagging here before we do.

**Comment by ccorda** [comment]
I believe on the WP engine side, it still needs to be master.

**Comment by kylehotchkiss** [comment]
Finally figured out what I saw - if you try to deploy before WP Engine implements your SSH key, it'll say "branch master is not found" which is similar to what github does after you rename branches. Threw me off before and again today.

**Comment by ccorda** [comment]
@kylehotchkiss was it just a message that through you off, but then you were able to proceed? Or was there more to it?
