### ISSUE TITLE
getContent() in lib/wordpress.js returns duplicate data under 2 keys

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-next#119]
Currently when you run `getContent()` you get two keys with duplicate records:
```
{
    post
    contentNode
}
```

Caused by this line of code:
https://github.com/patronage/bubs-next/blob/main/website/src/lib/wordpress.js#L246-L249

This a little unneeded weight on static pages or dynamic page getInitialProps. It also isn't clear which one to use and our code might be referencing both. I propose we just stick with `contentNode` to not get too far from the graphql structure. We just had `post` in there to maintain compatibility with our previous `getPost()` function which didn't use `contentNode`

**Comment by ccorda** [comment]
I agree and am pro this in WordPress.js.

Inside of `getStaticProps()`, I do prefer shaping the data a little bit so that you do have simpler variable names:

```
return {
    props: {
      globals: {
        ...globals,
        pageOptions: data.contentNode?.acfPageOptions,
      },
      preview,
      post: data.contentNode,
      flexSections:
        data.contentNode?.template?.acfFlex?.flexContent || null,
      template: data.contentNode?.template?.templateName || null,
    },
    revalidate: 10,
  };
```

**Comment by ccorda** [comment]
@kylehotchkiss is this one fixed by recent work? Or is it still open?

**Comment by kylehotchkiss** [comment]
I caught one more place in wordpress.js that wasn't returning the graphql response consistently, which is now resolved. I agree that getStaticProps is the best way to flatten the data structure (or fall back to default values if needed)
