### ISSUE TITLE
Routing support for Post IDs 

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-next#125]
While working with preview mode (#30), I found that draft posts only will return their ID and not their slug. Our routing system is based on slugs, so for preview mode, i've patched in support for it in `[[...slug]]` if the URLs first parameter is `/preview/`. `/preview/10` would render the preview for the post ID of 10.

Is there a better way to approach handling post IDs instead of slugs in our router? They're only likely to ever be needed while in preview mode, so maybe something like `if (preview mode && !isNaN(Number(slug param from url)))` to try to cast number only slugs to be treated like IDs while in preview mode

**Comment by kylehotchkiss** [comment]
There's a secondary ID based routing challenge to think about here for preview mode - when we get a post ID, we only send it to the root `[[...slug]].js` page. If the post has a post type that needs to be handled by another path in `pages/`, we don't currently have a way of configuring that in the preview mode API code. Is there an easier way to solve this (like grabbing the expected draft post URL from graphql) than trying to make a routing table for post types to paths in the API file?

**Comment by ccorda** [comment]
The code from the next/examples folder is already doing something similar, it checks if the slug is a number:

```
// The slug may be the id of an unpublished post
  const isId = Number.isInteger(Number(slug));
  const isSamePost = isId
    ? Number(slug) === postPreview.id
    : slug === postPreview.slug;
```

In my testing, this graphql:

```
query GetContent($slug: ID!) {
  contentNode(id: $slug, idType: URI, asPreview: true) {
    __typename
    databaseId
    id
    isPreview
    link
    slug
    uri
    status
    isRestricted
    ... on NodeWithTitle {
      title
    }
    previewRevisionDatabaseId
    previewRevisionId
  }
}
```

works in all of the following conditions:

```
{ "slug": "?p=1243" } // a "post" that is previewed without ever having a slug
{ "slug": "/news/some-draft-post/"} // a post that is saved with a slug, but not published. can also be ?
{ "slug": "p=932"} // same as the last post, but accessing with it's preview ID
{ "slug": "?p=1246" } // a nested page without slug.  its link response value is `http://localhost:8000/?page_id=1246`
{ "slug": "/top-level/sub-page/" } // a nested draft post with slug

----

So my conclusion would be that we would always check URI, either the URI of the path (including nested ones for pages), or if is a numeric ID, then checking `?p={$slug}`.





```

**Comment by ccorda** [comment]
One other note, I believe that the intent is that a given post has both a published state, and a revision version. This should be controllable with the `asPreview` variable:

The intent of this is here:
https://github.com/wp-graphql/wp-graphql/issues/1312

There is a bug that may or may not be effecting this:
https://github.com/wp-graphql/wp-graphql/issues/1673

Note that the WP example checks revision as an alternate option:
https://github.com/vercel/next.js/blob/canary/examples/cms-wordpress/lib/api.js#L160-L172

**Comment by kylehotchkiss** [comment]
We mostly solved this in preview mode with this block of code in `getContent()` 

https://github.com/patronage/bubs-next/blob/main/website/src/lib/wordpress.js#L185-L216

It determines if we're in preview mode, reads the last segment of the URL as a post ID if so, and generates a working `uri` for that post based on Wordpress' strange conventions for doing so (posts, pages, and custom posts all have totally different `uri` syntaxes)

as far as previewing revisions goes, preview mode supports it _but_ the post ID for a revision to a published post is not the same as the posts original ID. The graphql to get revisions within getContent() would have been gnarly. Preview mode is complicated and this seemed like an OK compromise to make for now to get it working.

Thanks for help brainstorming here Cam, this ticket turned out to be the solution that ultimately unlocked preview mode for us!
