### ISSUE TITLE
routeChangeComplete not correctly configured with useRouter

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-next#126]
Currently routeChangeComplete event listener is not connected to the `useRouter()` hook: https://github.com/patronage/bubs-next/blob/main/website/src/pages/_app.js#L22-L34 

I found that it wasn't firing for me on page changes. I adjusted the syntax to follow the [`routeChangeComplete` syntax in Next docs](https://nextjs.org/docs/api-reference/next/router#usage-6) and then the page change events fired for me as expected. I don't understand why no error messages occurred with the current code configuration as this fails pretty silently. Since we've been using GTM which can track pageview events on its own, this wasn't showing in analytics data either.

**Comment by ccorda** [comment]
FWIW I just tried on another site and it worked no problem:
![Screen Shot 2021-07-21 at 2 53 17 PM](https://user-images.githubusercontent.com/45271/126565144-c331d096-c18d-4def-968a-c26b27b5d80c.png)

From reading the PR, their reasoning is here:
https://github.com/vercel/next.js/pull/16846

Glad we're updating to follow their syntax, but it's not like old sites will have broken analytics.
