### ISSUE TITLE
WP Engine Auto Wordpress Updates failing

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-next#128]
the `bubsnext` WP Engine install was pretty dated (wp 5.5 instead of 5.8) so I tried to update it from WP Engine dashboard. It fails pretty quickly after and emails this back to us:

> The specific failed test consists of checking your environment(s) before and after the update to ensure we receive a 200 (OK) response, which usually confirms that no fatal errors have occurred.
> As a result of the tests failing, we have reverted the following environment(s) to the previous version:

I then ran a backup of the install in WP Engine and proceeded to update the instance manually from the WP dashboard, where it succeeded immediately, with no errors on `/` or `/graphql`. I think we should resolve the WP engine auto updates for ease of site maintenance and to make sure we're not unintentionally blocking WP engine from applying security updates to sites.

I'm not sure which specific path WP Engine's updater verifies for the update test, but if it's `/`, maybe we could switch the redirect from being a HTTP status code to a html file with 200 response and meta redirect header - people aren't going to just  be stumbling upon the WP engine domain so this slower redirect doesn't seem to be a concern.

**Comment by ccorda** [comment]
Good flag. Can you reach out to their support to see if there is a way around it? I'm hesitant not to 301 , I don't want google accidentally indexing anything.

**Comment by kylehotchkiss** [comment]
I ended up chatting with somebody technical at WP Engine and they first told me that the check for a 200 response from `/` is how the auto updater determines whether to start the backup and whether to consider it a success (along with all the auto-rollback functionality).

Since the 301 redirect is important, I asked if we could attempt to send a 200 if a specific useragent is detected and they responded with this:

```The smoke test curls http://localhost:6789 with headers “Host: $sitedomain” and “Cookie:wpengine_no_cache=1” as well as user agent “Mozilla/5.0 (compatible; WPEBot)”.

I do believe that this is how our platform handles the smoke test for the wordpress updates.```

I believe we can check for `WPEBot` useragent or `wpengine_no_cache` cookie before sending the 301 redirect to Vercel, and then return a 200, which would allow our headless sites to receive wordpress updates from WP Engine directly. 

Given that we might even be missing on security updates without this, we should try to ensure this functionality works before our 1.0 release.

**Comment by ccorda** [comment]
Great, I like that solve.
