### ISSUE TITLE
Preview mode: Create new read-only WP role with less privileges

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-next#129]
Currently a preview mode user account needs to be an `editor`. While an end user of bubs next has zero access to the graphql user because the session token only exists on the server side, we can take security a step further - we can create a new role just for graphql's user to use that has read access to unpublished posts and pages, but no write access to anything.

Role permission docs: https://wordpress.org/support/article/roles-and-capabilities/#read_private_posts
Assigning these same permissions to each CPT docs: https://developer.wordpress.org/reference/functions/register_post_type/#capability_type

**Comment by ccorda** [comment]
@kylehotchkiss I believe we can close this, as we're not creating a preview mode user. Can you confirm?

**Comment by kylehotchkiss** [comment]
Preview mode no longer uses a user but creates an access token for the currently logged in admin to access content with. This token is unique to the admin and not shared with the others. We don't need any new role/permissions adjusts given that.
