### ISSUE TITLE
404 template

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#13]
* [ ] Lightly style
* [ ] Load in `not-found` wp page if it exists
* [ ] Trigger a [GA event](https://www.solodev.com/blog/web-design/how-to-track-404-events-using-google-analytics-and-google-tag-manager.stml
)

**Comment by sscummings** [comment]
Partial example: https://github.com/patronage/wearehome/commit/19349495839c2e3bc2319d802971456617682d1c

**Comment by ccorda** [comment]
Issue moved to [patronage/fired-up-launch #71](https://github.com/patronage/fired-up-launch/issues/71) via [**ZenHub**](https://www.zenhub.com/)
