### ISSUE TITLE
Global Options Pre-populated

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#139]
Currently we ship with theme options disabled (in wordpress.js), and on a recent project when we went to uncomment they weren't working. We have everything setup for them in wordpress.js and in functions.php, I think we should enable a simple one (for footer group -- maybe a copyright text field), and use it.

**Comment by kylehotchkiss** [comment]
Closed by cb28a6b30d0906bcc720338b4bff1d3149743a71
