### ISSUE TITLE
Webhooks to refresh URLs after publish

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#14]
Currently we have a low cached time set on both `posts/index` and `posts/{slug}` so that when you go to it, next will look in the background and refetch the content.

Say a new post is published, you then go to the post, you're going to see the old post until you refresh.

If we were to have a webhook that pinged the URL, then when a user went to check it out they'd already get the fresh copy.

And then in future versions of Next, will be all set to implement the following:

> Up next, we will be working on a supplemental RFC to address two additional incremental static generation capabilities:

> Re-generating and invalidating multiple pages at once (like your blog index and a certain blog post)
Re-generating by listening to events (like CMS webhooks), ahead of user traffic

**Comment by kylehotchkiss** [comment]
We've moved towards GraphCDN as a caching layer for many projects, and include the ability to flush graphcdn's cache upon publishing a post. That is being tracked in https://github.com/patronage/bubs-next/issues/143. Can we close this one out?

**Comment by ccorda** [comment]
Yeah, we don't need this any more.
