### ISSUE TITLE
GraphCDN Integration

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-next#143]
GraphCDN is a caching layer that lives between Wordpress and Next.js. It's been helpful on several recent installs where Next.js usage was high due to repetitive GraphQL requests. Getting sites setup has been pretty easy, but there's a few things we can do to make the integration tighter

* [x] Document ideal GraphCDN/GraphQL plugin configuration values (considering preview mode, etc)
* [x] Implement targeted GraphCDN purge caching when a post in Wordpress is updated

**Comment by ccorda** [comment]
The google login plugin breaks cache, need to add our cookies handler to clear.

**Comment by ccorda** [comment]
In addition to adding docs (which are ready), let's also use graphcdn in our default env.sample (and on our live testing site)

**Comment by ccorda** [comment]
We have graphcdn, we have docs now, closing out.
