### ISSUE TITLE
Preview Mode Feedback

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#162]
1) As Preview mode is a core feature, I think our framework should work without an [ACF Pro](https://www.advancedcustomfields.com/pro/) license. Now I realize with Flex and Other global variable options we are pushing people that way, but those can be removed if a project isn't using pro pretty easily. Using a WP [theme_mod](https://www.usablewp.com/learn-wordpress/wordpress-customizer/theme-mods-vs-options-in-wordpress/) feels like an easy enough alternative, is suppored in core, and isn't the sort of thing a non-developer would need access to (so gating is probably a good thing)

2) Having used it on a few sites, I've now seen it conflict with site headers. What about adding a `location` param, with values of `top` and `bottom`? This gives an easy way to change position.

3) When a logged in user clicks the clickable permalink under the titile, I like that we're processing it. But that processing isn't working, it's generating an error when trying to go to:
`http://localhost:3000/api/preview/?code=${code}&slug=/posts/test-post/`

I know it's caused by this, so I think this case just needs to be accounted for (not sure if the solve is to pass in an ID as well, or to change some of the logic)

```
if (!id) {
   return res.status(401).json({ message: 'Invalid request' });
}
```

**Comment by kylehotchkiss** [comment]
Thanks for feedback here Cam. I'm glad we've had some collective experience rolling out preview mode so we can find the places where the process needs to improve.

> As Preview mode is a core feature, I think our framework should work without an ACF Pro license. Now I realize with Flex and Other global variable options we are pushing people that way, but those can be removed if a project isn't using pro pretty easily. Using a WP theme_mod feels like an easy enough alternative, is suppored in core, and isn't the sort of thing a non-developer would need access to (so gating is probably a good thing)

This is just for the preview URL while on staging, correct? We don't need variables for the production site exposed in the admin

> Having used it on a few sites, I've now seen it conflict with site headers. What about adding a location param, with values of top and bottom? This gives an easy way to change position.

Sounds good

>  it's generating an error when trying to go to:

The ID is needed in the get preview metadata graphql request. The pathname (currently called slug) is needed for some redirects. I'm in favor of always sending in ID, and changing the handling slightly if a `slug=` is present.

**Comment by ccorda** [comment]
> This is just for the preview URL while on staging, correct? We don't need variables for the production site exposed in the admin.

Correct Kyle, it's just for changing the preview url:
https://github.com/patronage/bubs-next/pull/163/files#diff-20eecad0ba703888babca7fc1edbb5495a0a26e3fe30f7cec59d4ddf4ab3e463L24

Let's use that PR to resolve these issues, then merge in.
