### ISSUE TITLE
wpgraphql.php cleanup

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#190]
Currently we have a file included with everything commented out.

I think we should update so that the file explains this is a place for graphql customizations, and have an example of customizing the number of posts to return:

https://whatjackhasmade.co.uk/gatsby-wordpress-increase-wpgraph-query-limit/

That number can come from the top level functions.php file

**Comment by kylehotchkiss** [comment]
Closed by https://github.com/patronage/bubs-next/pull/262
