### ISSUE TITLE
Pin dependencies

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#225]
Today we ran into an issue where our a site intended for Next 12.1 started getting 12.2 which had several errors.

We've typically pinned dependencies to insure consistency across projects, my rec would be to update all to be exact, e.g. for next "12.1.6" instead of "^12.1.6", and also to add `save-exact=true` to .npmrc.

I confirmed this will still work with our `npx npm-check-updates -i` that we typically run to upgrade things.

**Comment by kylehotchkiss** [comment]
Closed by https://github.com/patronage/bubs-next/pull/259
