### ISSUE TITLE
Next 13

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#238]
Assuming they release a new version at their conference later this month, some things we should have on our radar:

* Using the new next/image
* Anything server components
* New layouts/routing

**Comment by ccorda** [comment]
It looks like they are keeping app and 'legacy' pretty distinct. So for us it would be a matter of upgrading to 13.1:
https://nextjs.org/blog/next-13-1

And also updating to use the new next/image.

**Comment by ccorda** [comment]
While we're in here, can we bump .nvmrc, and the package.json engines to 18?

**Comment by kylehotchkiss** [comment]
This also requires converting <Link><a> to just <Link>. Upgrade instructions: https://nextjs.org/docs/upgrading#link-component
