### ISSUE TITLE
WP Engine git deploy update

### ISSUE THREAD

**Issue by chrisherold** [patronage/bubs-next#240]
In https://github.com/patronage/bubs-next/blob/main/wordpress/_build/deploy.sh we check for `master` branch on WP Engine's git deploy remote. This works for legacy projects where they preserved the `master` branch but on new project this errors with `error: src refspec master does not match any` since they only provide a `main` branch now.

I believe (but we should double check) that legacy projects also have a `main` branch on the deploy remote so we should be able to update all `master` references to `main`

**Comment by ccorda** [comment]
I'm not sure how to tell legacy from new. But I just tried a couple projects, and switching to main had no issue.
