### ISSUE TITLE
Preview mode for draft & preview posts

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#30]
* Next has a [preview mode](https://nextjs.org/docs/advanced-features/preview-mode) for viewing non-public posts.
* The WP + Next example has [instructions on how to do auth](https://github.com/vercel/next.js/tree/canary/examples/cms-wordpress#step-5-add-authentication-for-preview-mode-optional), and how to implement preview mode.
* WP is going to need to link to the correct API routes for previewing, which [can be accomplished via filters](https://www.cyberciti.biz/faq/php-wordpress-change-post-url-via-preview_post_link-filter/)

**Comment by ccorda** [comment]
New WP has application passwords that might make this easier.
https://wptavern.com/wordpress-5-6-to-introduce-application-passwords-for-rest-api-authentication

**Comment by ccorda** [comment]
WP engine has a new headless framework that might make both the Next and WP sides simpler to implement:
https://github.com/wpengine/headless-framework/tree/canary/docs/previews

**Comment by kylehotchkiss** [comment]
@ccorda, I’ve been trying to figure out preview mode for Wordpress today to see how Next’s built in option and the Headless Framework implemented it. While I understand the headless framework’s implementation of a /preview route is preferable and redirecting to Wordpress login is nice, it looks pretty complicated to roll out both on the WP and Next side without just switching to their framework. The JS pieces don’t look like something that can be easily pulled out and cloned on our side, it seems like we’d need to actually load their library and call their functions, which doesn’t seem ideal. If we wanted to do that, just grabbing that functionality piecemeal would take me a while as I don’t really understand how all the pieces work together.

Next.js built-in preview mode’s technical setup makes sense to me and we could expand it to behave more similarly to Headless Framework, specifically by making a /preview catch-all that checks for preview mode and either redirects to the page in preview mode if the preview mode cookies are set OR redirects to Wordpress login, and then post-login, starts preview mode through Wordpress and redirects back to the page in preview mode. We could show a black bar on the top of the page when in preview mode with a link to edit post & exit preview mode too.

I’m not sure how to proceed further at the moment, please let me know when you have a few minutes and let’s hop on a call and figure it out.

**Comment by kylehotchkiss** [comment]
Preview mode has been implemented for several months now, closing.
