### ISSUE TITLE
Best Practice for loading icons

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#4]
Would like to make it easy to grab icons, and style them using css to easily adjust size, colors (including hover) without needing to rely on a bulky webfont.

Success criteria:

* Allow me to include a custom SVG
* Allow me to get an SVG from a public source.

**Comment by chrisherold** [comment]
React-icons has been great on our initial projects and definitely think we should continue to use.

I used `svgr` recently and it worked great for custom icons, there's a little bit of manual work as you have to run the CLI and then put the svg code in the correct file. But svgr nicely shrinks the svg code and has helpful options like replacing attributes and setting the size.

**Comment by ccorda** [comment]
We have react-icons in source, and next now has svg loading baked in. Closing out.
