### ISSUE TITLE
Sample Blog Index Page

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#5]
Requirements: 

* [x] Support pagination ([example](https://medium.com/javascript-in-plain-english/simple-pagination-in-next-js-using-react-paginate-562830c00279))
* [x] category/tags/authors on single
* [x] category/tags/authors on index

**Comment by kylehotchkiss** [comment]
@ccorda Since #35 was merged, can we close this one?

**Comment by ccorda** [comment]
Yes @kylehotchkiss good here, thank you.
