### ISSUE TITLE
Husky consolidation and v5

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#53]
Traditionally in `bubs`, we had husky perform two checks:

1. see if the `yarn.lock` changed, and if so let dev know they need to run `yarn install`
2. set chmod permissions on acf json

Now that we have both wp and wordpress with their own package.json files, we're in a little bit of trouble.

We also want to add in linting as a pre-commit hook on our `website` folder.

Husky has also updated to version 5 which works a little differently:
https://typicode.github.io/husky/#/?id=usage

My recommendation would be to:

* Update to Husky version 5
* Remove Susky from `wordpress`
* Have Husky live inside of `website`

**Comment by kylehotchkiss** [comment]
@ccorda I got this error when `git pull`ing one of our projects today:

```sh: ./.githooks/post-merge.sh: Permission denied
husky > post-merge hook failed (cannot be bypassed with --no-verify due to Git specs)``` 

Is this related or should I file a new ticket?

**Comment by ccorda** [comment]
Looks like they're up to 6 now, and hopefully it fixes some of the issues that 5 had. Still leaving us on 4 for now:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6

**Comment by kylehotchkiss** [comment]
Up to 7 now: https://github.com/typicode/husky/releases/tag/v7.0.0
