### ISSUE TITLE
Redirect Management

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#57]
Something clients often want are the ability to set and manage redirects, including for renamed posts.

If using the premium version of Yoast, those redirects are in graphql:
https://github.com/ashhitch/wp-graphql-yoast-seo/issues/38

* https://github.com/vercel/next.js/issues/4931#issuecomment-512787861
* https://www.npmjs.com/package/nextjs-redirect

**Comment by ccorda** [comment]
Looks like you can do dynamic redirects in the next config file:
https://github.com/vercel/next.js/discussions/15344

I'm going to give this a try tomorrow.

**Comment by kylehotchkiss** [comment]
Did we find a way to execute redirects after build in any recent projects?

**Comment by ccorda** [comment]
This one is implemented. Have a few cleanup tasks/bugs that will get fixed in a new PR shortly.
