### ISSUE TITLE
YouTube optimization

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#59]
* https://twitter.com/rauchg/status/1323029946877444096
* https://github.com/paulirish/lite-youtube-embed

**Comment by kylehotchkiss** [comment]
We've been enjoying [`react-player`](https://github.com/CookPete/react-player) for a few recent projects. I realize it doesn't optimize quite to the extent the `lite-youtube-embed` module does but we have found it a nice convention for embeds.

**Comment by ccorda** [comment]
Closing, not getting to into front-end modules in this repo (but do reccomend react-player)
