### ISSUE TITLE
Font loading optimization

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#60]
Lee Robinson had a post/thread this week on optimizing Font performance on Vercel/Next:

* https://twitter.com/leeerob/status/1349527966083145736
* https://leerob.io/blog/fonts

**Comment by ccorda** [comment]
* [ ] Remove remote google fonts example
* [ ] Show example of self-hosted font and preload

**Comment by kylehotchkiss** [comment]
Next.js will actually inline Google Fonts in the pages static HTML if you load them with the correct syntax in versions > 10.2: https://nextjs.org/blog/next-10-2#automatic-webfont-optimization

We should document this and endorse it more - it's one of their good new features that doesn't get the praise it deserves. I bet they'll get adobe fonts inlined one day too 🤞🏼

**Comment by kylehotchkiss** [comment]
Update: typekit fonts are included in Next's auto webfont optimization https://nextjs.org/docs/basic-features/font-optimization

It seems like all you need to do is just add these fonts to <Head>. Is there any further action needed for this ticket?

**Comment by ccorda** [comment]
removed one old font reference to a preconnect that is no longer needed in https://github.com/patronage/bubs-next/commit/7a6c21765e81ffc17fc7c8575bac6c7fef66dcd9
