### ISSUE TITLE
WordPress home page

### ISSUE THREAD

**Issue by chrisherold** [patronage/bubs-next#66]
We need to pull in the homepage that's set in WP > Settings > Reading and make sure we're set to render that if desired

**Comment by ccorda** [comment]
I believe this is no longer an issue -- since we're using URIs now, the homepage checks for `/`, which is the page that WP sets as the homepage. Can you confirm @chrisherold?  refs #194

**Comment by chrisherold** [comment]
Yea I think that's right, but will double check
