### ISSUE TITLE
Custom Post Type Routing

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#72]
Ideally, we'd make it easy to support a "simple" custom post type, with the following requirements:

* Load a default number of posts on an index page
* Ability to paginate either through an ajax/inline click to load more, and/or through paged links
* A single of the post.

And a more complex version that also adds:
* Category, Tags, And custom taxonomies

It'd be nice to have separate components for index/single displays.

The actual graphql that calls should be easy to adjust as different post types might have different requirements.

We need to make sure that these routes support query strings, either from cache posting via WordPress, or things like UTM params.

Something we should look at is the `<NextTemplateLoader>` from the new wpengine headless framework:
https://github.com/wpengine/headless-framework/tree/canary/docs/templating

**Comment by kylehotchkiss** [comment]
https://www.wpgraphql.com/2021/12/23/query-any-page-by-its-path-using-wpgraphql/

NodeByUri might solve this

**Comment by ccorda** [comment]
Dupe of #133
