### ISSUE TITLE
Remove plugin prettier/recommended from .eslintrc

### ISSUE THREAD

**Issue by imjared** [patronage/bubs-next#95]
Part of the benefit of Prettier it is that it runs automatically, allowing the dev to code with whatever style looks/feels right at the moment then on commit, code gets standardized. Prettier errors via eslint are not only unnecessary but are distracting during development as they get mixed in with _actual_ eslint errors and warnings.

Example:
<img src="https://user-images.githubusercontent.com/525011/115040897-e9892500-9e9f-11eb-8b4d-d203f4354c28.png" width="75%" />

**Comment by ccorda** [comment]
Reviewing 1.0 issues and trying to understand this one...

https://nextjs.org/docs/basic-features/eslint#usage-with-prettier

> ESLint also contains code formatting rules, which can conflict with your existing Prettier setup. We recommend including eslint-config-prettier in your ESLint config to make ESLint and Prettier work together.

Are you ok leaving `eslint-config-prettier`, but then removing `eslint-plugin-prettier`? I've submitted a PR #145 to test this approach out.

**Comment by ccorda** [comment]
One regression I just realized, we had VSCode configured to disable prettier, and run eslint fix on save. We need to adjust that if we're going this route.

**Comment by ccorda** [comment]
Recently upgraded stylelint and eslint, believe we are all good here.
